version: '3.2'
services:

#########################################
# node core api instances
#########################################
  api1:
    image: carbasketfactory:v1
    container_name: carbasket_apis1
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api2:
    image: carbasketfactory:v1
    container_name: carbasket_apis2
    restart: always
    ports:
      - 4001:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network   

  api3:
    image: carbasketfactory:v1
    container_name: carbasket_apis3
    restart: always
    ports:
      - 4002:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api4:
    image: carbasketfactory:v1
    container_name: carbasket_apis4
    restart: always
    ports:
      - 4003:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api5:
    image: carbasketfactory:v1
    container_name: carbasket_apis5
    restart: always
    ports:
      - 4004:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api6:
    image: carbasketfactory:v1
    container_name: carbasket_apis6
    restart: always
    ports:
      - 4005:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network   

  api7:
    image: carbasketfactory:v1
    container_name: carbasket_apis7
    restart: always
    ports:
      - 4006:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api8:
    image: carbasketfactory:v1
    container_name: carbasket_apis8
    restart: always
    ports:
      - 4007:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  

  api9:
    image: carbasketfactory:v1
    container_name: carbasket_apis9
    restart: always
    ports:
      - 4008:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api10:
    image: carbasketfactory:v1
    container_name: carbasket_apis10
    restart: always
    ports:
      - 4009:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  

  api11:
    image: carbasketfactory:v1
    container_name: carbasket_apis11
    restart: always
    ports:
      - 4010:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api12:
    image: carbasketfactory:v1
    container_name: carbasket_apis12
    restart: always
    ports:
      - 4011:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network    

  api13:
    image: carbasketfactory:v1
    container_name: carbasket_apis13
    restart: always
    ports:
      - 4012:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api14:
    image: carbasketfactory:v1
    container_name: carbasket_apis14
    restart: always
    ports:
      - 4013:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      
      
  api15:
    image: carbasketfactory:v1
    container_name: carbasket_apis15
    restart: always
    ports:
      - 4014:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api16:
    image: carbasketfactory:v1
    container_name: carbasket_apis16
    restart: always
    ports:
      - 4015:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network   

  api17:
    image: carbasketfactory:v1
    container_name: carbasket_apis17
    restart: always
    ports:
      - 4016:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api18:
    image: carbasketfactory:v1
    container_name: carbasket_apis18
    restart: always
    ports:
      - 4017:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api19:
    image: carbasketfactory:v1
    container_name: carbasket_apis19
    restart: always
    ports:
      - 4018:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api20:
    image: carbasketfactory:v1
    container_name: carbasket_apis20
    restart: always
    ports:
      - 4019:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network   

  api21:
    image: carbasketfactory:v1
    container_name: carbasket_apis21
    restart: always
    ports:
      - 4020:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api22:
    image: carbasketfactory:v1
    container_name: carbasket_apis22
    restart: always
    ports:
      - 4021:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  

  api23:
    image: carbasketfactory:v1
    container_name: carbasket_apis23
    restart: always
    ports:
      - 4022:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api24:
    image: carbasketfactory:v1
    container_name: carbasket_apis24
    restart: always
    ports:
      - 4023:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  

  api25:
    image: carbasketfactory:v1
    container_name: carbasket_apis25
    restart: always
    ports:
      - 4024:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api26:
    image: carbasketfactory:v1
    container_name: carbasket_apis26
    restart: always
    ports:
      - 4025:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network    

  api27:
    image: carbasketfactory:v1
    container_name: carbasket_apis27
    restart: always
    ports:
      - 4026:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api28:
    image: carbasketfactory:v1
    container_name: carbasket_apis28
    restart: always
    ports:
      - 4027:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  
  api29:
    image: carbasketfactory:v1
    container_name: carbasket_apis29
    restart: always
    ports:
      - 4028:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api30:
    image: carbasketfactory:v1
    container_name: carbasket_apis30
    restart: always
    ports:
      - 4029:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network   

  api31:
    image: carbasketfactory:v1
    container_name: carbasket_apis31
    restart: always
    ports:
      - 4030:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api32:
    image: carbasketfactory:v1
    container_name: carbasket_apis32
    restart: always
    ports:
      - 4031:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api33:
    image: carbasketfactory:v1
    container_name: carbasket_apis33
    restart: always
    ports:
      - 4032:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api34:
    image: carbasketfactory:v1
    container_name: carbasket_apis34
    restart: always
    ports:
      - 4033:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network   

  api35:
    image: carbasketfactory:v1
    container_name: carbasket_apis35
    restart: always
    ports:
      - 4034:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api36:
    image: carbasketfactory:v1
    container_name: carbasket_apis36
    restart: always
    ports:
      - 4035:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  

  api37:
    image: carbasketfactory:v1
    container_name: carbasket_apis37
    restart: always
    ports:
      - 4036:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api38:
    image: carbasketfactory:v1
    container_name: carbasket_apis38
    restart: always
    ports:
      - 4037:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  

  api39:
    image: carbasketfactory:v1
    container_name: carbasket_apis39
    restart: always
    ports:
      - 4038:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api40:
    image: carbasketfactory:v1
    container_name: carbasket_apis40
    restart: always
    ports:
      - 4039:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network    

  api41:
    image: carbasketfactory:v1
    container_name: carbasket_apis41
    restart: always
    ports:
      - 4040:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api42:
    image: carbasketfactory:v1
    container_name: carbasket_apis42
    restart: always
    ports:
      - 4041:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      
      
  api43:
    image: carbasketfactory:v1
    container_name: carbasket_apis43
    restart: always
    ports:
      - 4042:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api44:
    image: carbasketfactory:v1
    container_name: carbasket_apis44
    restart: always
    ports:
      - 4043:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network   

  api45:
    image: carbasketfactory:v1
    container_name: carbasket_apis45
    restart: always
    ports:
      - 4044:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api46:
    image: carbasketfactory:v1
    container_name: carbasket_apis46
    restart: always
    ports:
      - 4045:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api47:
    image: carbasketfactory:v1
    container_name: carbasket_apis47
    restart: always
    ports:
      - 4046:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api48:
    image: carbasketfactory:v1
    container_name: carbasket_apis48
    restart: always
    ports:
      - 4047:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network   

  api49:
    image: carbasketfactory:v1
    container_name: carbasket_apis49
    restart: always
    ports:
      - 4048:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api50:
    image: carbasketfactory:v1
    container_name: carbasket_apis50
    restart: always
    ports:
      - 4049:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  

  api51:
    image: carbasketfactory:v1
    container_name: carbasket_apis51
    restart: always
    ports:
      - 4050:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api52:
    image: carbasketfactory:v1
    container_name: carbasket_apis52
    restart: always
    ports:
      - 4051:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  

  api53:
    image: carbasketfactory:v1
    container_name: carbasket_apis53
    restart: always
    ports:
      - 4052:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api54:
    image: carbasketfactory:v1
    container_name: carbasket_apis54
    restart: always
    ports:
      - 4053:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network    

  api55:
    image: carbasketfactory:v1
    container_name: carbasket_apis55
    restart: always
    ports:
      - 4054:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api56:
    image: carbasketfactory:v1
    container_name: carbasket_apis56
    restart: always
    ports:
      - 4057:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  
  api57:
    image: carbasketfactory:v1
    container_name: carbasket_apis57
    restart: always
    ports:
      - 4056:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api58:
    image: carbasketfactory:v1
    container_name: carbasket_apis58
    restart: always
    ports:
      - 4057:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network    

  api59:
    image: carbasketfactory:v1
    container_name: carbasket_apis59
    restart: always
    ports:
      - 4058:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network      

  api60:
    image: carbasketfactory:v1
    container_name: carbasket_apis60
    restart: always
    ports:
      - 4059:4000
    volumes:
      - ./:/usr/src/app      
    networks:
      - app-network  
#########################################
# Nginx Load Balancer
#########################################
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancers
    ports:
      - 80:80  # Expose Nginx on port 80
    depends_on:
      - api1
      - api2
      - api3
      - api4
      - api5
      - api6
      - api7
      - api8
      - api9
      - api10
      - api11
      - api12
      - api13
      - api14
      - api15
      - api16
      - api17
      - api18
      - api19
      - api20
      - api21
      - api22
      - api23
      - api24
      - api25
      - api26
      - api27
      - api28
      - api29
      - api30
      - api31
      - api32
      - api33
      - api34
      - api35
      - api36
      - api37
      - api38
      - api39
      - api40
      - api41
      - api42
      - api43
      - api44
      - api45
      - api46
      - api47
      - api48
      - api49
      - api50
      - api51
      - api52
      - api53
      - api54
      - api55
      - api56
      - api57
      - api58
      - api59
      - api60
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

#########################################
# networks
######################################### 

networks:
  app-network:
    driver: bridge
    
